name: "Test Docker Compose"
# author: "Ryo Kuroyanagi, Liam Laverty"
# description: "Checks if the docker app has launched, based on the article: https://dev.to/ku6ryo/script-to-check-if-docker-booted-for-github-actions-138g"

on:
  push:
    branches: [ "main", "stage", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  all:
    name: Docker compose test containers are created, running, and healthy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Create postgres volume
        run: docker volume create ideal_umbrella_postgres_data
      
      - name: Docker compose up
        run: docker-compose --env-file .github/workflows/workflow-scripts/.env.github_actions_env up -d
      
      - name: Make the script files executable
        shell: bash
        run: chmod +x .github/workflows/workflow-scripts/docker-all-apps-run-healthcheck.sh
      
      - name: Test Postgres running
        shell: bash
        run: .github/workflows/workflow-scripts/docker-all-apps-run-healthcheck.sh example_postgres_sql_server_db 60
      
      - name: Test MsSQL running
        shell: bash
        run: .github/workflows/workflow-scripts/docker-all-apps-run-healthcheck.sh example_umbraco_sql_server_db 60
      
      - name: Test Umbraco Backoffice running
        shell: bash
        run: .github/workflows/workflow-scripts/docker-all-apps-run-healthcheck.sh EXAMPLE_PROJECT_NAME_umbraco_backoffice 60
      
      - name: Test Umbraco Frontend running
        shell: bash
        run: .github/workflows/workflow-scripts/docker-all-apps-run-healthcheck.sh EXAMPLE_PROJECT_NAME_umbraco_frontend 60