name: "Test Docker Compose"
# author: "Ryo Kuroyanagi, Liam Laverty"
# description: "Checks if the docker app has launched, based on the article: https://dev.to/ku6ryo/script-to-check-if-docker-booted-for-github-actions-138g"

on:
  push:
    branches: [ "main", "stage", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  get_runner:
    name: get_runner
    if: ${{ always() }}
    runs-on: ubuntu-latest
    outputs:
      RUNNER: ${{ runner.name }}
    steps: 
      - run: echo "selected runner = ${{ runner.name }}"

  build_and_launch_to_docker:
    name: build_and_launch_to_docker_app
    needs: get_runner
    runs-on: ${{needs.get_runner.outputs.RUNNER}}
    steps:
      - uses: actions/checkout@v3
      - name: Docker Create postgres volume
        run: docker volume create ideal_umbrella_postgres_data
      - name: Docker compose up
        run: docker-compose --env-file .env.example up -d --build sql_postgres_db
  test_apps_are_running:
    name: Test Applications are running
    runs-on: ${{needs.get_runner.outputs.RUNNER}}
    needs: build_and_launch_to_docker
    steps:
      - uses: actions/checkout@v3
      - name: Make the script files executable
        run: chmod +x .github/workflows/workflow-scripts/docker-all-apps-run-healthcheck.sh
      - name: Test Postgres running
        run: .github/workflows/workflow-scripts/docker-all-apps-run-healthcheck.sh example_postgres_sql_server_db 30
