name: Docker Image CI - Posgis

on:
  push:
    branches: [ "main", "stage", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build-mssql-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Postgres/Postgis Docker image
      run: docker build . --file IU.Docker/dockerfile.postgres --tag my-image-name:$(date +%s)